org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Silenciar avisos de Gradle
org.gradle.warning.mode=none

# ESTA LÍNEA ES CRÍTICA: Fuerza a Gradle a ignorar Java 25 y usar Java 17
org.gradle.java.home=C\:/Program Files/Microsoft/jdk-17.0.19.10-hotspot

