org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false

# Senior Fix 1: Forzar el uso de JDK 17 (Microsoft)
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.19.10-hotspot

# Senior Fix 2: Bypasear el chequeo de variables de entorno conflictivas
android.overridePathCheck=true
