name: Build Windows Desktop

on:
  push:
    branches: []
    tags:
      - 'win-v*' # Se activa EXCLUSIVAMENTE al crear un tag como win-v1.0.0

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.44.8'

      - name: Build Windows Release
        working-directory: ./Web_Desktop
        run: |
          flutter pub get
          flutter build windows --release

      - name: Compress Windows Build
        run: |
          Compress-Archive -Path "Web_Desktop/build/windows/x64/runner/Release/*" -DestinationPath "auristv-windows-x64.zip"

      - name: Upload Windows App to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: auristv-windows-x64.zip
          body_path: RELEASE_NOTES.md
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
