name: Build Flutter APK

on:
  push:
    branches: []
    tags:
      - 'v*' # Se activa EXCLUSIVAMENTE al crear un tag como v1.0.0

jobs:
  build:
    name: Build Android APKs (Split by ABI)
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para crear la Release y subir los APKs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.44.8'

      - name: Build Split APKs Release
        run: |
          cd Movil
          flutter pub get
          flutter build apk --release --split-per-abi

      - name: Upload APKs to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Movil/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            Movil/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            Movil/build/app/outputs/flutter-apk/app-x86_64-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
